### ISSUE TITLE
Support quoted entries

### ISSUE THREAD

**Issue by jamierocks** [jamiemansfield/csv#2]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at me.jamiemansfield.csv.CsvParser.parseLine(CsvParser.java:99)
	at me.jamiemansfield.csv.CsvParser.lambda$parse$0(CsvParser.java:71)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at me.jamiemansfield.csv.CsvParser.parse(CsvParser.java:70)
	at Repository.getMcpMappings(Repository.java:204)
	at Repository.getYarnToMcpMappings(Repository.java:249)
	at Main.run(Main.java:27)
	at Main.main(Main.java:13)
```

**Comment by jamierocks** [comment]
Here's a more helpful stacktrace. The issue is the lack of support for quoted entries.

```
Exception in thread "main" me.jamiemansfield.csv.CsvParsingException: Failed to parse CSV line [415]: "field_73005_l,updateLCG,2,"Contains the current Linear Congruential Generator seed for block updates. Used with an A value of 3 and a C value of 0x3c6ef35f, producing a highly planar series of values ill-suited for choosing random blocks in a 16x128x16 field.""
	at me.jamiemansfield.csv.CsvParser.lambda$parse$0(CsvParser.java:78)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at me.jamiemansfield.csv.CsvParser.parse(CsvParser.java:72)
	at Repository.getMcpMappings(Repository.java:204)
	at Repository.getYarnToMcpMappings(Repository.java:249)
	at Main.run(Main.java:27)
	at Main.main(Main.java:13)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at me.jamiemansfield.csv.CsvParser.parseLine(CsvParser.java:107)
	at me.jamiemansfield.csv.CsvParser.lambda$parse$0(CsvParser.java:75)
	... 8 more
```
